# Generated by Django 5.0.2 on 2024-03-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileAnalyzer', '0002_reviewmodel_delete_filemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='Review',
        ),
    ]
