# Generated by Django 5.0.2 on 2024-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileAnalyzer', '0004_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewModes',
            field=models.JSONField(default=list),
        ),
    ]
