# Generated by Django 5.0.2 on 2024-11-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileAnalyzer', '0008_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='meteorScore',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='review',
            name='rougeScore',
            field=models.FloatField(default=-1),
        ),
    ]
