# Generated by Django 5.0.2 on 2024-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileAnalyzer', '0009_review_meteorscore_review_rougescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(default='python', max_length=100),
        ),
    ]
